const randomID = () => Math.floor(Math.random() * 1000000);

function createBookmark(url, title) {
  return {
    url,
    title,
    id: randomID(),
    type: "",
    parentID: "",
    index: "",
  };
}

const topSites = [
  "amazon.com",
  "youtube.com",
  "en.wikipedia.org",
  "twitter.com",
  "facebook.com",
  "yelp.com",
  "reddit.com",
  "imdb.com",
  "fandom.com",
  "pinterest.com",
  "tripadvisor.com",
  "instagram.com",
  "walmart.com",
  "craigslist.org",
  "ebay.com",
  "linkedin.com",
  "play.google.com",
  "healthline.com",
  "etsy.com",
  "indeed.com",
  "apple.com",
  "espn.com",
  "webmd.com",
  "fb.com",
  "nytimes.com",
  "google.com",
  "cnn.com",
  "merriam-webster.com",
  "gamepedia.com",
  "microsoft.com",
  "target.com",
  "homedepot.com",
  "quora.com",
  "nih.gov",
  "rottentomatoes.com",
  "netflix.com",
  "quizlet.com",
  "weather.com",
  "mapquest.com",
  "britannica.com",
  "businessinsider.com",
  "dictionary.com",
  "zillow.com",
  "mayoclinic.org",
  "bestbuy.com",
  "theguardian.com",
  "yahoo.com",
  "msn.com",
  "usatoday.com",
  "medicalnewstoday.com",
  "urbandictionary.com",
  "usnews.com",
  "foxnews.com",
  "genius.com",
  "allrecipes.com",
  "spotify.com",
  "glassdoor.com",
  "forbes.com",
  "cnet.com",
  "finance.yahoo.com",
  "irs.gov",
  "lowes.com",
  "mail.yahoo.com",
  "aol.com",
  "steampowered.com",
  "washingtonpost.com",
  "usps.com",
  "office.com",
  "retailmenot.com",
  "wiktionary.org",
  "paypal.com",
  "foodnetwork.com",
  "hulu.com",
  "live.com",
  "cbssports.com",
  "wayfair.com",
  "ca.gov",
  "bleacherreport.com",
  "macys.com",
  "accuweather.com",
  "xfinity.com",
  "go.com",
  "techradar.com",
  "groupon.com",
  "investopedia.com",
  "yellowpages.com",
  "steamcommunity.com",
  "bankofamerica.com",
  "chase.com",
  "wellsfargo.com",
  "ally.com",
  "discover.com",
  "capitalone.com",
  "creditkarma.com",
  "mint.com",
  "truist.com",
  "npr.org",
  "apartments.com",
  "roblox.com",
  "huffpost.com",
  "books.google.com",
  "bbb.org",
  "expedia.com",
  "wikihow.com",
  "ign.com",
  "wowhead.com",
  "weather.gov",
  "noaa.gov",
].sort();

const otherBookmarks = [
  ["https://lucaseverett.dev", "Lucas Everett"],
  ["https://toolbardial.com", "Toolbar Dial"],
];

const bookmarksFolder = [
  ["https://www.amazon.com", "Amazon"],
  ["https://www.facebook.com", "Facebook"],
  ["https://www.instagram.com", "Instagram"],
  ["https://www.linkedin.com", "LinkedIn"],
  ["https://twitch.tv", "Twitch"],
  ["https://www.twitter.com", "Twitter"],
  ["https://www.youtube.com", "YouTube"],
];

const topSitesGlobal = [
  "google.com",
  "google.co.br",
  "google.de",
  "google.fr",
  "google.co.uk",
  "google.it",
  "google.co.jp",
  "google.co.in",
  "google.es",
  "amazon.com",
  "amazon.co.jp",
  "amazon.de",
  "amazon.co.uk",
  "amazon.co.in",
  "yahoo.com",
  "yahoo.co.jp",
];

const devBookmarks = () => {
  if (process.env.NODE_ENV === "development") {
    return [
      {
        url: "",
        title: "Top Sites - US",
        id: "3",
        type: "",
        parentID: "",
        index: "",
      },
      {
        url: "",
        title: "Top Sites - Global",
        id: "4",
        type: "",
        parentID: "",
        index: "",
      },
    ];
  } else {
    return [];
  }
};

export const allBookmarks = {
  1: {
    bookmarks: [
      ...bookmarksFolder.map((b) => createBookmark(b[0], b[1])),
      {
        url: "",
        title: "Other Bookmarks",
        id: "2",
        type: "",
        parentID: "",
        index: "",
      },
    ],
    parentID: "0",
    title: "Bookmarks Bar",
  },
  2: {
    bookmarks: [
      ...otherBookmarks.map((b) => createBookmark(b[0], b[1])),
      ...devBookmarks(),
    ],
    parentID: "1",
    title: "Other Bookmarks",
  },
  3: {
    bookmarks: topSites.map((b) => createBookmark(`https://${b}`, b)),
    parentID: "2",
    title: "Top Sites - US",
  },
  4: {
    bookmarks: topSitesGlobal.map((b) => createBookmark(`https://${b}`, b)),
    parentID: "2",
    title: "Top Sites - Global",
  },
};
