export const wallpapers = [
  {
    id: "SandDune",
    title: "Sand Dune",
    filename: "SandDune.jpg",
    thumbnail: "SandDune_thumb.png",
    url:
      "https://pixabay.com/photos/sand-dune-background-nature-desert-2848098/",
    category: "nature",
  },
  {
    id: "WavySand",
    title: "Wavy Sand",
    filename: "WavySand.jpg",
    thumbnail: "WavySand_thumb.png",
    url: "https://www.pexels.com/photo/wavy-sand-2931286/",
    category: "nature",
  },
  {
    id: "Galaxy",
    title: "Milky Way Galaxy",
    filename: "Galaxy.jpg",
    thumbnail: "Galaxy_thumb.png",
    url: "https://unsplash.com/photos/etiMpySyrnI",
    category: "nature",
  },
  {
    id: "BeachForest",
    title: "Beach Forest",
    filename: "BeachForest.jpg",
    thumbnail: "BeachForest_thumb.png",
    url:
      "https://www.pexels.com/photo/seashore-near-on-forest-trees-on-bird-s-eye-view-1123484/",
    category: "nature",
  },
  {
    id: "Water",
    title: "Water",
    filename: "Water.jpg",
    thumbnail: "Water_thumb.png",
    url: "https://unsplash.com/photos/cfR-V1QuEKw",
    category: "nature",
  },
  {
    id: "Flowers",
    title: "Flowers",
    filename: "Flowers.jpg",
    thumbnail: "Flowers_thumb.png",
    url: "https://unsplash.com/photos/urUdKCxsTUI",
    category: "nature",
  },
  {
    id: "SnowCoveredMountainwithSunnySky",
    title: "Snow Covered Mountain",
    filename: "SnowCoveredMountainwithSunnySky.jpg",
    thumbnail: "SnowCoveredMountainwithSunnySky_thumb.png",
    url: "https://unsplash.com/photos/0vw4InAC-yM",
    category: "nature",
  },
  {
    id: "DesertDay",
    title: "Desert Day",
    filename: "DesertDay.png",
    thumbnail: "DesertDay_thumb.png",
    url: "https://stock.adobe.com/101124546",
    category: "nature",
  },
  {
    id: "DesertNight",
    title: "Desert Night",
    filename: "DesertNight.png",
    thumbnail: "DesertNight_thumb.png",
    url: "https://stock.adobe.com/315957514",
    category: "nature",
  },
  {
    id: "Crayons",
    title: "Crayons",
    filename: "Crayons.jpg",
    thumbnail: "Crayons_thumb.png",
    url: "https://stock.adobe.com/213611570",
    category: "artistic",
  },
  {
    id: "Underwater",
    title: "Underwater",
    filename: "Underwater.jpg",
    thumbnail: "Underwater_thumb.png",
    url: "https://stock.adobe.com/29107448",
    category: "nature",
  },
  {
    id: "HorizonLight",
    title: "Horizon Light",
    filename: "HorizonLight.png",
    thumbnail: "HorizonLight_thumb.png",
    url: "https://lucaseverett.dev",
    category: "abstract",
  },
  {
    id: "HorizonDark",
    title: "Horizon Dark",
    filename: "HorizonDark.png",
    thumbnail: "HorizonDark_thumb.png",
    url: "https://lucaseverett.dev",
    category: "abstract",
  },
  {
    id: "AbstractPurple",
    title: "Abstract Purple",
    filename: "AbstractPurple.jpg",
    thumbnail: "AbstractPurple_thumb.png",
    url:
      "https://pixabay.com/illustrations/purple-abstract-background-1780371/",
    category: "abstract",
  },
  {
    id: "Gradient1",
    title: "Gradient 1",
    filename: "RiceFlower.png",
    thumbnail: "RiceFlower_thumb.png",
    url: "https://www.ls.graphics/meshgradients",
    category: "abstract",
  },
  {
    id: "Gradient2",
    title: "Gradient 2",
    filename: "ColumbiaBlue.png",
    thumbnail: "ColumbiaBlue_thumb.png",
    url: "https://www.ls.graphics/meshgradients",
    category: "abstract",
  },
  {
    id: "Gradient3",
    title: "Gradient 3",
    filename: "Fuchsia.png",
    thumbnail: "Fuchsia_thumb.png",
    url: "https://www.ls.graphics/meshgradients",
    category: "abstract",
  },
  {
    id: "Gradient4",
    title: "Gradient 4",
    filename: "VioletBlue.png",
    thumbnail: "VioletBlue_thumb.png",
    url: "https://www.ls.graphics/meshgradients",
    category: "abstract",
  },
];
