export const wallpapers = [
  {
    id: "WavySand",
    title: "Wavy Sand",
    filename: "wavy-sand-2931286.jpg",
    thumbnail: "wavy-sand-2931286_thumb.png",
    url: "https://www.pexels.com/photo/wavy-sand-2931286/",
  },
  {
    id: "SandDune",
    title: "Sand Dune",
    filename: "sand-2848098.jpg",
    thumbnail: "sand-2848098_thumb.png",
    url:
      "https://pixabay.com/photos/sand-dune-background-nature-desert-2848098/",
  },
  {
    id: "Galaxy",
    title: "Milky Way Galaxy",
    filename: "stephen-wheeler-etiMpySyrnI-unsplash.jpg",
    thumbnail: "stephen-wheeler-etiMpySyrnI-unsplash_thumb.png",
    url: "https://unsplash.com/photos/etiMpySyrnI",
  },
  {
    id: "BeachForest",
    title: "Beach Forest",
    filename: "seashore-near-on-forest-trees-on-bird-s-eye-view-1123484.jpg",
    thumbnail:
      "seashore-near-on-forest-trees-on-bird-s-eye-view-1123484_thumb.png",
    url:
      "https://www.pexels.com/photo/seashore-near-on-forest-trees-on-bird-s-eye-view-1123484/",
  },
  {
    id: "Water",
    title: "Water",
    filename: "yucar-fotografik-cfR-V1QuEKw-unsplash.jpg",
    thumbnail: "yucar-fotografik-cfR-V1QuEKw-unsplash_thumb.png",
    url: "https://unsplash.com/photos/cfR-V1QuEKw",
  },
  {
    id: "Flowers",
    title: "Flowers",
    filename: "anthony-delanoix-urUdKCxsTUI-unsplash.jpg",
    thumbnail: "anthony-delanoix-urUdKCxsTUI-unsplash_thumb.png",
    url: "https://unsplash.com/photos/urUdKCxsTUI",
  },
  {
    id: "SnowCoveredMountainwithSunnySky",
    title: "Snow Covered Mountain",
    filename: "wladislaw-sokolowskij-0vw4InAC-yM-unsplash.jpg",
    thumbnail: "wladislaw-sokolowskij-0vw4InAC-yM-unsplash_thumb.png",
    url: "https://unsplash.com/photos/0vw4InAC-yM",
  },
  {
    id: "DesertDay",
    title: "Desert Day",
    filename: "DesertDay.png",
    thumbnail: "DesertDay_thumb.png",
    url: "https://stock.adobe.com/101124546",
  },
  {
    id: "Crayons",
    title: "Crayons",
    filename: "AdobeStock_213611570.jpeg",
    thumbnail: "AdobeStock_213611570_thumb.png",
    url: "https://stock.adobe.com/213611570",
  },
  {
    id: "Underwater",
    title: "Underwater",
    filename: "AdobeStock_29107448.jpeg",
    thumbnail: "AdobeStock_29107448_thumb.png",
    url: "https://stock.adobe.com/29107448",
  },
  {
    id: "AbstractPurple",
    title: "Abstract Purple",
    filename: "purple-1780371.png",
    thumbnail: "purple-1780371_thumb.png",
    url:
      "https://pixabay.com/illustrations/purple-abstract-background-1780371/",
  },
  {
    id: "Gradient1",
    title: "Gradient 1",
    filename: "RiceFlower.png",
    thumbnail: "RiceFlower_thumb.png",
    url: "https://www.ls.graphics/meshgradients",
  },
  {
    id: "Gradient2",
    title: "Gradient 2",
    filename: "ColumbiaBlue.png",
    thumbnail: "ColumbiaBlue_thumb.png",
    url: "https://www.ls.graphics/meshgradients",
  },
  {
    id: "Gradient3",
    title: "Gradient 3",
    filename: "Fuchsia.png",
    thumbnail: "Fuchsia_thumb.png",
    url: "https://www.ls.graphics/meshgradients",
  },
  {
    id: "Gradient4",
    title: "Gradient 4",
    filename: "VioletBlue.png",
    thumbnail: "VioletBlue_thumb.png",
    url: "https://www.ls.graphics/meshgradients",
  },
];
